# Generated by Django 6.0.3 on 2026-06-24 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Neuer Chat', max_length=200)),
                ('mode', models.CharField(choices=[('AUTO', 'AUTO — Router bestimmt Profil'), ('MANUELL', 'MANUELL — User stellt Parameter'), ('CODING', 'CODING — Dokument-Ingest Workflow')], default='AUTO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('susi', 'SUSI')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tok_per_sec', models.FloatField(blank=True, null=True)),
                ('antwortzeit_sek', models.FloatField(blank=True, null=True)),
                ('tokens_generiert', models.IntegerField(blank=True, null=True)),
                ('llm_model', models.CharField(blank=True, default='', max_length=100)),
                ('router_profil', models.CharField(blank=True, default='', max_length=50)),
                ('reranker_used', models.BooleanField(blank=True, null=True)),
                ('chunks_gefunden', models.IntegerField(blank=True, null=True)),
                ('chunks_nach_reranking', models.IntegerField(blank=True, null=True)),
                ('rewritten_query', models.TextField(blank=True, default='')),
                ('quelldateien', models.JSONField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chat')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('target_folder', models.CharField(default='docs/queue/', max_length=200)),
                ('suggested_filename', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend — wartet auf Review'), ('approved', 'Freigegeben — bereit für Ingest'), ('rejected', 'Abgelehnt')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('router_profil', models.CharField(blank=True, default='', max_length=50)),
                ('quelldateien', models.JSONField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, default='AUTO', max_length=10)),
                ('review_notiz', models.TextField(blank=True, default='')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='core.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
