# Generated by Django 6.0.3 on 2026-07-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='manuell_settings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
