# Generated by Django 6.0.3 on 2026-07-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chat_manuell_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='mode',
            field=models.CharField(choices=[('AUTO', 'AUTO — Router bestimmt Profil'), ('MANUELL', 'MANUELL — User stellt Parameter'), ('CHUNKING', 'CHUNKING — Dokument-Aufbereitung für Ingest')], default='AUTO', max_length=10),
        ),
    ]
